name: Create Github Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate dark stats card
        uses: readme-tools/github-readme-stats-action@v1.1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=onedark
          path: profile/stats_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate light stats card
        uses: readme-tools/github-readme-stats-action@v1.1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=default
          path: profile/stats_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate dark trophy card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: username=${{ github.repository_owner }}&row=3&column=5&theme=onedark
          path: profile/trophy_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate light trophy card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: username=${{ github.repository_owner }}&row=3&column=5&theme=default
          path: profile/trophy_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update Github Stats" || exit 0
          git push
